version: "3.9"
volumes:
  grafana-data:
services:
  prometheus:
    image: prom/prometheus:v2.43.0
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  grafana:
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/ksp2_prometheus_exporter_dashboard.json
    image: grafana/grafana-oss:9.5.1
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml:ro
      - ./dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml:ro
      - ./ksp2_prometheus_exporter_dashboard.json:/var/lib/grafana/dashboards/ksp2_prometheus_exporter_dashboard.json:ro